### ISSUE TITLE
How do you set the http port?

### ISSUE THREAD

**Issue by edwardotis** [pusher/pusher-websocket-java#110]
I am using a pusher-fake server for development, and I need to set a custom port so my app can send the trigger() event to the correct port of the local pusher-fake server.

In the equivalent python library, the Pusher constructor accepts an http port override. However, the port override appears to be missing from the constructor of Pusher as well as PusherOptions.

https://github.com/tristandunn/pusher-fake

**Comment by kn100** [comment]
Please see http://pusher.github.io/pusher-websocket-java/ for setWsPort and setWssPort
