### ISSUE TITLE
Transitive dependency is not publicly available

### ISSUE THREAD

**Issue by vach** [pusher/pusher-websocket-java#117]
http://imgur.com/4EO1Fi9

Latest version is 1.3.0

I'm keeping having all sorts of problems with your library
please fix this asap, if i downgrade dependency version, your service stops sending data after few hours of streaming, if i use latest version this is what i get... blocked with pusher again

**Comment by jpatel531** [comment]
Hey there, have you included the clojars repo to your build file. E.g for gradle:

repositories { maven { url 'http://clojars.org/repo' } }

**Comment by vach** [comment]
Yes i did, although clojars is another headache they have some habit to be offline...
It is enought to look here http://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket
this is the dependency that causes the issue and its not from clojars but from maven... 
which shows that latest version is 1.3.0

**Comment by vach** [comment]
I tried 1.3.0 and it fails with NoSuchMethod exception somewhere deep.
I dont understand am i only one who wanted to use pusher java client?
where do i get this 1.3.1 jar?

**Comment by vach** [comment]
OK i'm done working with pusher. good luck

**Comment by jpatel531** [comment]
Hi @vach - on clojars.org, the repository declared as a source for java-websocket in our build files, the version is 1.3.1 https://clojars.org/org.java-websocket/java-websocket

If you are willing to give it another go, I'd be more than happy to double-check your build.gradle / pom.xml to see if there might be something in that.
