### ISSUE TITLE
Unable to pass JSON array as data in PrivateChannel

### ISSUE THREAD

**Issue by emitchel** [pusher/pusher-websocket-java#122]
Because the trigger method (in `PrivateChannelImpl`) first parses the data into a `Map<>`, any data not in a JSON Object format, a `JsonSyntaxException` is thrown. The data we send over is very fragile and cannot be altered without issue, but it is also a JSON array, therefore thrown exception . After forking the repo and simply removing the attempt to parse into Map and just passing the data as is, all previously successful calls still work and our endpoint now works as expected.

Should we remove this attempt to parse into Map.class? (`@PrivateChannelImpl#trigger(final String eventName, final String data)`)

Code snippet in question:

```
        //Doesn't seem necessary
        final Map userData = GSON.fromJson(data, Map.class);

        final Map<Object, Object> jsonPayload = new LinkedHashMap<Object, Object>();
        jsonPayload.put("event", eventName);
        jsonPayload.put("channel", name);
        jsonPayload.put("data", userData);

        final String jsonMessage = GSON.toJson(jsonPayload);
        connection.sendMessage(jsonMessage);`
```

The other reason why I bring this up is because the iOS library _doesn't_ do this, it simply passes the data as-is, so why does Android library do this?

**Comment by sschendel** [comment]
Any update on this issue?  Worthy of a pull request?

**Comment by kn100** [comment]
Closing due to age
