### ISSUE TITLE
callback method when paired device disconnected

### ISSUE THREAD

**Issue by aurk** [pusher/pusher-websocket-java#124]
Is there any callback method that indicates, paired device(s) is/are disconnected from pusher.

**Usecase**
We are developing game in which if any player is left(whether because off internet connection or disconnect from pusher), then other player get notification that paired player is disconnected so that we can calculate things.

**Comment by zmarkan** [comment]
We do have the concept of _Presence Channels_, which should give you that information: https://pusher.com/docs/client_api_guide/client_presence_channels

**Comment by kn100** [comment]
Closing due to age
