### ISSUE TITLE
Detect if I am subscribed to a channel?

### ISSUE THREAD

**Issue by carlonzo** [pusher/pusher-websocket-java#126]
Hi,
I just received a crash because I was trying to resubscribe to the same channel. Is there a way to retrieve the list of channel I am subscribed to? or how can I know if I am subscribed to a specific channel?

thank you!

**Comment by zmarkan** [comment]
At the moment, you can get a channel if it exists with by calling `pusher.getChannel("channelName");`. If it doesn't exist it will return `null`, and that's when you can call `pusher.subscribe(...)`

There is currently no way of getting all subscribed channels, but I'll keep it in mind for the future, thanks.

**Comment by erlangp** [comment]
thanks @zmarkan :+1:

**Comment by fzs1994** [comment]
Hey, I'm getting error when calling `pusher.getChannel("channelName");` I'm on pusher-js v7.0.1
