### ISSUE TITLE
In ChannelIml.Java throw new IllegalArgumentException

### ISSUE THREAD

**Issue by ankit22451847** [pusher/pusher-websocket-java#127]
throw new IllegalArgumentException("Channel name " + channelName + " is invalid. Private channel names must start with \"private-\" and presence channel names must start with \"presence-\"");

please check and correct regex in 

protected String[] getDisallowedNameExpressions() {
        return new String[]{"^private-.*", "^presence-.*"};
    }

in above it ^ symbol tell negotiation means except private- it matches.

if am am wrong then plz tell me solution.

my error code is

 Channel channel = pusher.subscribe("private-mousemoves");

        channel.bind("new_message", new SubscriptionEventListener() {
            @Override
            public void onEvent(String channelName, String eventName, final String data) {
                //if (channelName.equalsIgnoreCase("ankit")) {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        Gson gson = new Gson();
                        Message message = gson.fromJson(data, Message.class);
                        messageAdapter.add(message);
                        messagesView.setSelection(messageAdapter.getCount() - 1);
                    }

                });
                //}
            }

output:

Caused by: java.lang.IllegalArgumentException: Channel name private-mousemoves is invalid. Private channel names must start with "private-" and presence channel names must start with "presence-"

**Comment by zmarkan** [comment]
You'd need to use the class `PrivateChannel` for that, not the standard `Channel`: https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java#L113

**Comment by erlangp** [comment]
thanks @zmarkan
