### ISSUE TITLE
not able to subscribe private channel

### ISSUE THREAD

**Issue by ankit22451847** [pusher/pusher-websocket-java#128]
I think that there is problem in:

 if(channelName.matches(disallowedPattern)) {
                    throw new IllegalArgumentException("Channel name " + channelName + " is invalid. Private channel names must start with \"private-\" and presence channel names must start with \"presence-\"");
                }

it throw exception

**Comment by zmarkan** [comment]
I think this is a duplicate of https://github.com/pusher/pusher-websocket-java/issues/127
