### ISSUE TITLE
Pusher unsubscribe not working

### ISSUE THREAD

**Issue by sirajsolutelabs** [pusher/pusher-websocket-java#146]
Hi,

I am using pusher for websocket and push notification purpose. The issue currently happening for quite a long time to me is that the channels are not getting unsubscribed on using the below code:

`Pusher pusher = new Pusher(Config.PUSHER_APP_KEY);
pusher.unsubscribe(channelName);`

On logout, I am calling the above code, still at my login page, I am getting notification, which is very danger for me. I am using below gradle dependencies:

`compile 'com.pusher:pusher-java-client:1.4.0'
compile 'com.pusher:pusher-websocket-android:0.5.0'`

Please guide me through this.

**Comment by zmarkan** [comment]
Hello,

What are you trying to unsubscribe from? Is it a native Android push notification  or a websocket channel? 

Also, the `Pusher` object is meant to be instantiated only once and then reused, rather than instantiated each time you might need it.

Thanks

**Comment by sirajsolutelabs** [comment]
Hi,

I am unsubscribing a native web socket channel.

The problem is I have different types of public channel and 1 private and 1 presence channel. All of them has unique methods for subscribe tasks. Like subscribePublicChannel, subscribePrivateChannel etc.

In that class, I also have unsubscribe common for all channels, which is not working. Is it due to I am creating pusher object everytime?

**Comment by zmarkan** [comment]
Yes, the `Channel` instances aren't shared between `Pusher` instances, so I'm guessing that's why it won't work. 
Can you please try reusing the `Pusher` object and check if that worked?

Thanks

**Comment by sirajsolutelabs** [comment]
Please look the method of private channel subscription. Here I am initializing custom authorizer and on Connect we are setting the headers as per the documentations:

`final CustomHttpAuthorizer authorizer = new CustomHttpAuthorizer(BuildConfig.API_URL +
                "/v1/notifications/authorize/");
        HashMap<String, String> params = new HashMap<>();
        params.put("auth_key", authKey);
        authorizer.setQueryStringParameters(params);
        PusherOptions options = new PusherOptions().setEncrypted(true).setAuthorizer(authorizer);
        final Pusher pusher = new Pusher(Config.PUSHER_APP_KEY, options);

        pusher.connect(new ConnectionEventListener() {
            @Override
            public void onConnectionStateChange(ConnectionStateChange connectionStateChange) {
                if (connectionStateChange.getCurrentState().toString().equalsIgnoreCase("CONNECTED")) {
                    String socketId = pusher.getConnection().getSocketId();
                    HashMap<String, String> parameters = new HashMap<>();
                    parameters.put(socketIdKey, socketId);
                    parameters.put(channelKey, channelName);
                    parameters.put(userIdKey, userId);
                    authorizer.setHeaders(parameters);

                    String eventUserId = userId.replace("-", ".");
                        PrivateChannel privateChannel = pusher.subscribePrivate(channelName);
                        privateChannel.bind(eventUserId, new PrivateChannelEventListener() {
                            @Override
                            public void onAuthenticationFailure(String s, Exception e) {
                               
                            }

                            @Override
                            public void onSubscriptionSucceeded(String s) {
                                
                            }

                            @Override
                            public void onEvent(String channelName, String eventName, final String data) {
                               bindData(data);
                            }
                        });

                } else {
                    Log.d(TAG, "Private onConnectionStateChange() called with: connectionStateChange = " +
                            "[" + connectionStateChange.getCurrentState() + "]");
                }
            }

            @Override
            public void onError(String s, String s1, Exception e) {
                Log.d(TAG, "onError() called with: s = [" + s + "], s1 = [" + s1 + "], e = [" + e + "]");
            }
        });`

Same is for Presence channel. Now if I am creating the global pusher instance as you said. I will not get the channel name to authorise as there are multiple channels. So do you have any sample or something which specifies this king of global pusher instance.

**Comment by zmarkan** [comment]
Are you calling `connect` multiple times?

**Comment by zmarkan** [comment]
Ah, I see what's going on now. I think you are trying to pass the channel Name to your `CustomHTTPAuthorizer` manually? 

Every time you call `subscribePrivate` or `subscribePresence` a call to `authorizer.authorize(channelName, socketId)` is triggered - so I think it's best to move the following logic in that call instead, something like this:

```

    @Override
    public String authorize(String channelName, String socketId) throws AuthorizationFailureException {

        // create headers here, and attach them to the request you're building:

        HashMap<String, String> parameters = new HashMap<>();
        parameters.put(socketIdKey, socketId);
        parameters.put(channelKey, channelName);
        parameters.put(userIdKey, userId);

        //...
```
