### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by ruXlab** [pusher/pusher-websocket-java#150]
### What is the issue?
When `setCluster("eu")` is not specified for `PusherOptions` app is crashing with erro
> InvalidFrameException: more than 125 octets

### Is it a crash report? Submit stack traces or anything that you think would help

```
07-25 20:28:35.633 14840-14857/app.com.android I/System.out: Got error An exception was thrown by the websocket - null (com.pusher.java_websocket.exceptions.InvalidFrameException: more than 125 octets)
07-25 20:28:35.633 14840-14857/app.com.android W/System.err: com.pusher.java_websocket.exceptions.InvalidFrameException: more than 125 octets
07-25 20:28:35.634 14840-14857/app.com.android W/System.err:     at com.pusher.java_websocket.drafts.Draft_10.translateSingleFrame(Draft_10.java:322)
07-25 20:28:35.634 14840-14857/app.com.android W/System.err:     at com.pusher.java_websocket.drafts.Draft_10.translateFrame(Draft_10.java:284)
07-25 20:28:35.634 14840-14857/app.com.android W/System.err:     at com.pusher.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:320)
07-25 20:28:35.634 14840-14857/app.com.android W/System.err:     at com.pusher.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
07-25 20:28:35.634 14840-14857/app.com.android W/System.err:     at com.pusher.java_websocket.client.WebSocketClient.run(WebSocketClient.java:184)

```

### Any improvements you suggest

Client can provide more human-readable exception related to the connection, for example `IllegalArgumentException` with text `No cluster provided` or `Provided cluster doesn't match settings`

-------------------------

CC @pusher/mobile

**Comment by gonzepge** [comment]
Same problem ... blocking.

**Comment by must2912** [comment]
same here

**Comment by kn100** [comment]
Hey all!

Firstly, sorry for the enormously slow response to this issue. We've identified the cause and should have a fix in production soon. 

You'll get this error when you try to connect to a cluster that doesn't contain your app.

**Comment by kn100** [comment]
Fixed :)
