### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by segunmicheal27** [pusher/pusher-websocket-java#153]
### What is the issue?
there is dependency conflict with http library 
... 

### Is it a crash report? Submit stack traces or anything that you think would help

Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.3.4 is ignored for debug as it may be conflicting with the internal version provided by Android.
...

### Any improvements you suggest
version need to be change to avoid conflict
...

---- 

CC @pusher/mobile

**Comment by zmarkan** [comment]
I don't think we have that dependency in our library. Are you using our server library by any chance? (`pusher-http-java`)
