### ISSUE TITLE
Next Release Build

### ISSUE THREAD

**Issue by damogallagher** [pusher/pusher-websocket-java#159]
### What is the issue?
NA
... 

### Is it a crash report? Submit stack traces or anything that you think would help
NA
...

### Any improvements you suggest
NA
Just wondering when the next release build of the pusher library will be?

...

---- 

CC @pusher/mobile

**Comment by zmarkan** [comment]
Hi, I'll make the release today after some testing.

**Comment by damogallagher** [comment]
Perfect, thank you @zmarkan

**Comment by zmarkan** [comment]
It's being propagated in Maven Central now, should be done in a few hours.
