### ISSUE TITLE
Private channel subscribe error.

### ISSUE THREAD

**Issue by ixxxxxx** [pusher/pusher-websocket-java#160]
### What is the issue?
I user pusher-java to subscribe a private channel, and it throw an error.
Here is my code 
```
    private void initPusher() {
        HttpAuthorizer authorizer = new HttpAuthorizer("https://myapi.com/v1/pusher/authenticate");
        authorizer.setHeaders(new HashMap<String, String>()
        {
            {
                put("Authorization", "Bearer" + AccessToken.readAccessToken());
            }
        });
        PusherOptions options = new PusherOptions().setAuthorizer(authorizer).setCluster(MYCLUSTER);
        Pusher pusher = new Pusher(MYAPIKEY, options);
        pusher.connect(new ConnectionEventListener() {
            @Override
            public void onConnectionStateChange(ConnectionStateChange connectionStateChange) {
                Log.i("Pusher", "Connection State Change: " + connectionStateChange.toString());

            }

            @Override
            public void onError(String s, String s1, Exception e) {
                Log.i("Pusher", String.format("Connection Error: [%s], exception was [%s]", s, e));
            }
        }, ConnectionState.ALL);

        PrivateChannel channel = pusher.subscribePrivate(("private-" + AccessToken.readAccessChannel()), new PrivateChannelEventListener() {
            @Override
            public void onAuthenticationFailure(String s, Exception e) {
                Log.i("Pusher", String.format("Authentication failure due to [%s], exception was [%s]", s, e));
            }

            @Override
            public void onSubscriptionSucceeded(String s) {
                Log.i("Pusher", "Private connection succeeded");
            }

            @Override
            public void onEvent(String channel, String event, String data) {
                Log.i("Pusher", data);
            }
        });
    }
```
... 

### Is it a crash report? Submit stack traces or anything that you think would help
```
Authentication failure due to [java.io.FileNotFoundException: https://myapi.com/v1/pusher/authenticate], exception was [com.pusher.client.AuthorizationFailureException: java.io.FileNotFoundException: https://myapi.com/v1/pusher/authenticate]
```
...

### Any improvements you suggest
I saw the same issue #119 ,but @anbu369 just close the issue.
And my gradle:
 ` compile 'com.pusher:pusher-java-client:1.5.0'`
...

---- 

CC @pusher/mobile

**Comment by ixxxxxx** [comment]
It seems the HttpAuthorizer's header lost some thing, so my api server return 401 error.
Is there any tools can log the request when pusher subscribe private channel send auth?

**Comment by zmarkan** [comment]
Thank you,

Whoa, the error message should definitely be better. `FileNotFoundException` doesn't tell you anything.

The only thing I can see from your code snippet is that there might be a space missing between `Bearer` and the actual token.
 
```
put("Authorization", "Bearer" + AccessToken.readAccessToken());
```
Maybe it should be `Bearer ` instead?

For checking the requests you could use a http proxy like Charles or similar to look at the requests. 
You could also check in your serverside logs what kind of requests are you getting with the token requests.

Could you double check that please and lmk what happens?

Thanks

**Comment by ixxxxxx** [comment]
Yes, it should be:
`put("Authorization", "Bearer " + AccessToken.readAccessToken());`
and I also lost some header for the api server.

I use Charles to check the request, but as pusher's connect is websockt, it seems pusher cannot connect through Charles' proxy. In the end, I let the php guy check the log in the server😂.

**Comment by malik082009** [comment]
@ixxxxxx and @zmarkan i am still facing the same issue, i used `put("Authorization", "Bearer " + AccessToken.readAccessToken());
`
but id did not worked. what i found is the `HttpAuthorizer` is throwing exception on this line:
// Read response
final InputStream is = connection.getInputStream(); in `authorize` method.
i do more debugging and find  `HttpURLConnection.getResponseMessage()` in `HttpAuthorizer` is **unauthorized**
