### ISSUE TITLE
Events are globally synchronized on a static lock (strange behaviour?)

### ISSUE THREAD

**Issue by ww3456** [pusher/pusher-websocket-java#166]
eventLock is a static member variable. It seems unusual that events on different Pusher instances will be synchronized. Is this actually intended? 

https://github.com/pusher/pusher-websocket-java/blob/4b3a60aac3080f2a7530395ac66a72fcfc081fbb/src/main/java/com/pusher/client/util/Factory.java#L102

If a global lock is not required, since the executor is single threaded, does the Runnable.run() method need any locking? The queueOnEventThread is synchronized which should take care of any initial threading issues.

**Comment by zmarkan** [comment]
There shouldn't really be multiple Pusher instances - just have 1 per application.  
I think you're right though, it doesn't seem necessary  to have the lock here. But is it causing any problems for you?

**Comment by ww3456** [comment]
I am planning on having data from 2 different sources (with different keys) subscribed by my application, which would require different Pusher instances. I don't see any reason why it shouldn't work as it is, but with unnecessary locking between the sources. Although for my purposes I doubt there will be a significant impact, so don't anticipate a problem as such. However, do you envisage any issues with removing this (unneeded) synchronization? Thanks.

**Comment by zmarkan** [comment]
I see - that makes sense if the data sources are different.
I _think_ you're right and it doesn't need that synchronised, but I need to go through the code to double check it, as well as test it out. 

I've created a ticket for it - please do let me know if you find any problems with your use-case in the meantime so I can prioritise it.
