### ISSUE TITLE
android java sdk wrong reponse just like encode its twice  

### ISSUE THREAD

**Issue by medozeus** [pusher/pusher-websocket-java#178]
first this is my php response

```
$data = array( 
"fname" =>"Altan",
"lname" => "Bayram",
"image" =>"https://i.pinimg.com/originals/a5/6d/1a/a56d1a6a6892d8647208313412e055ed.jpg",
"id"    => 1,
"user_id" => 50

);	
 
$user_channel = "private-p_{$id}"; 
$pusher->trigger($user_channel, 'typing', json_encode($data)); 

```

now the result of ` json_encode` all we know its 

`{"fname":"Altan","lname":"Bayram","image":"https:\/\/i.pinimg.com\/originals\/a5\/6d\/1a\/a56d1a6a6892d8647208313412e055ed.jpg","id":1,"user_id":50} `

but pusher its like encode its twice and the result its 

`"{\"fname\":\"Altan\",\"lname\":\"Bayram\",\"image\":\"https:\\\/\\\/i.pinimg.com\\\/originals\\\/a5\\\/6d\\\/1a\\\/a56d1a6a6892d8647208313412e055ed.jpg\",\"id\":1,\"user_id\":50}"`

but in `javascript sdk` its work without problem only in java sdk

**Comment by kn100** [comment]
Hi, 

Apologies for the slow reply! Is this still an issue for you?

**Comment by medozeus** [comment]
thank for your response i just used an library i forget its name might its
(Json) for parse the response

**Comment by kn100** [comment]
Alright awesome! I'll close it for now then.
