### ISSUE TITLE
How to trigger to a public channel?

### ISSUE THREAD

**Issue by umbertix** [pusher/pusher-websocket-java#180]
I'm trying to implement the client (in an Android app) and trigger into a public channel. But I don't see any way to do so.

I don't have an authentication endpoint and I don't want a have to implement it (I'm using it for a very dummy app). Is there any of stubing the authentication for a private channel?

I'm more than open to suggestions or other libraries if solves my problem.
CC @pusher/mobile

**Comment by kn100** [comment]
You're probably looking for https://github.com/pusher/pusher-http-java :)
