### ISSUE TITLE
State stuck on DISCONNECTING

### ISSUE THREAD

**Issue by ArtificialPB** [pusher/pusher-websocket-java#186]
### What is the issue?
When the client loses connection and after reaching max reconnection attempts (6), the state gets stuck on `DISCONNECTING`.

After debugging, the underlying connection was closed, as was the raw java Socket. Not familiar with the source code but it seems to me that something went wrong when calling `cancelTimeoutsAndTransitonToDisconnected()` in `WebSocketConnection.onClose()` function. The `Factory`'s `eventQueue` executor is still running, and it has 52 tasks queued. None get processed and no new ones get added. The last event in the queue is the shutdown hook so it never got processed.

After further inspecting the `eventQueue`'s `workQueue`, one of the tasks is returning an exception, but it's near the end of it:
```
java.net.UnknownHostException: ws.pusherapp.com
java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
java.net.Socket.connect(Socket.java:589)
sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
com.pusher.java_websocket.client.WebSocketClient.run(WebSocketClient.java:165)
java.lang.Thread.run(Thread.java:745)
```

**Comment by kn100** [comment]
Hey, are you still encountering this issue? I've got a possible fix but I wanted to know which version of the library you were using.

**Comment by ArtificialPB** [comment]
We are no longer using this library so I'm unable to comment if it's still happening or not. The issue was encountered using version `1.7.0`.

**Comment by sonologico** [comment]
This has been mitigated to some extent in the latest release. It could still happen if the queue does get stuck as in this issue. Please open a new issue if this happens to you.
