### ISSUE TITLE
Dependency declaration uses obsolete keyword Compile

### ISSUE THREAD

**Issue by kn100** [pusher/pusher-websocket-java#191]
### What is the issue?
When adding the dependency, the following error is observed
```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app
```

### Any improvements you suggest
Move to using `implementation` and `api`.
---- 

CC @pusher/mobile

**Comment by ben-j69** [comment]
@kn100 because we don't use compile anymore, instead we use implementation, why it is not clear to you ? The documentation of pusher is just outdated

**Comment by kn100** [comment]
Hi Ben,

It is clear, I just haven't had the time to update this library yet, but I didn't want to forget about this issue, which is why I added it as an issue :)

**Comment by ben-j69** [comment]
@kn100 do you need help ?

**Comment by kn100** [comment]
I will get around to this eventually - but if you want to submit a PR I'm happy to review! If there's other things that annoy you about this library too let me know. I've only recently started owning it so I am looking for things to fix/update/improve!
