### ISSUE TITLE
Invalid signature: Expected HMAC SHA256 hex digest of XXX, but got XXX

### ISSUE THREAD

**Issue by alizeec** [pusher/pusher-websocket-java#205]
### What is the issue?
Hello

I have this error 
{"event":"pusher:error","data":{"code":null,"message":"Invalid signature: Expected HMAC SHA256 hex digest of 264774.13368624:private-phone-company-509, but got 52aabdb73de6d1f04c8729e585eae54b71f40a2e9d2bfb1eaa695bd480682d7b"}}
 in onError() method of the ConnectionEventListener passed in parameter in pusher.connect(listener)

`

pusher?.connect(object: ConnectionEventListener{
            override fun onConnectionStateChange(change: ConnectionStateChange?) {
            }

            override fun onError(message: String?, code: String?, e: Exception?) {
                // error here
            }
        })
`

This is how I configured Pusher
`

val httpAuthorizer = HttpAuthorizer(endpoint)
        httpAuthorizer.setHeaders(authorizerHeaders)

        val pusherOptions = PusherOptions()
        pusherOptions.authorizer = httpAuthorizer
        pusherOptions.isEncrypted = isEncrypted

        pusher = Pusher(apiKey, pusherOptions)
`

The error occurs only with a private channel, it worked well with a public channel. On the iOS app, there is no problem with the same configuration.
The authentication call returns
`{"auth":"[API_KEY]:52aabdb73de6d1f04c8729e585eae54b71f40a2e9d2bfb1eaa695bd480682d7b","channel_data":"{DATA_ON_MY_USER}` 

Could you help me, please?
Thanks

---- 

CC @pusher/mobile

**Comment by kn100** [comment]
Incorrect HMAC Signature can mean a number of things.

Does the secret key being used in your authentication server correspond to the public app key in your client? You can check this in your Dashboard (dashboard.pusher.com). If you're using a different Channels app for your java client, you'll need a different auth endpoint.

Is the time on your server and client correct? 

This may relate to this resolved issue, which may contain a solution. If it helps, let me know please!

https://github.com/pusher/pusher-websocket-java/issues/144

**Comment by alizeec** [comment]
We use the right api key (the same than iOS and ReactJs apps, and it works on their side).
I'm using the channel app for staging and the auth endpoint is specific for staging.
I have the current time on my emulator, nothing custom on this side.

Once the auth endpoint response is received, we send 
`{"event":"pusher:subscribe","data":{"channel":"private-phone-company-509","auth":"c19aa170a96a48046263:187c8b33c30b8b82a152f9d06b9093afd406c7dc5e78c62ee9c1b4358052a7a0"}}` in socket connexion

For some reason, it uses only the signature and not the auth string [app_key]:[signature]

**Comment by marcaaron** [comment]
FWIW, I've found that when using _presence_auth_ iOS and web clients have no issues connecting to private channels, but Java does throws this error. Switching it to `socket_auth` for private channels was the fix for me.

**Comment by kn100** [comment]
@marcaaron could you provide me a bit more detail on exactly how you fixed this?

**Comment by marcaaron** [comment]
Sure! In our case, to authorize access for private channels we're using the PHP library which clearly mentions two separate authentication methods for private vs. presence channels. 

See readme [here](https://github.com/pusher/pusher-http-php/blob/43540be9536469f8eaec95a347d3f7532bac852c/README.md#authenticating-private-channels)

So the fix was to change `presence_auth` to `socket_auth` without providing any additional data.

```php
$pusher = new Pusher(...);
$pusher->socket_auth($channel, $socket);
```

I see now, however, that `presence-auth` calls `socket_auth` indirectly
https://github.com/pusher/pusher-http-php/blob/43540be9536469f8eaec95a347d3f7532bac852c/src/Pusher.php#L764-L772

And the `socket_auth` method returns an HMAC signature with additional data...
https://github.com/pusher/pusher-http-php/blob/43540be9536469f8eaec95a347d3f7532bac852c/src/Pusher.php#L724-L730

So what could be the issue here? Perhaps this is a bug with the Java client since it works fine for Swift and JavaScript clients?

**Comment by enginebai** [comment]
We had the same issue recently. We didn't change any thing on client and server side at all. Our pusher java sdk is `1.8.0`.  Any fix for this?

**Comment by kn100** [comment]
Hi all,

Is this happening for all your payloads or a small percentage? We've got a theory internally as to whats going on - but need more data to prove it.

Can you also tell me a bit about where and how your clients are deployed? I'm most interested in how they get access to the internet - are they behind a proxy? firewall? etc.

**Comment by enginebai** [comment]
It happened to our android app and on our private channel only, it was ok on presence channel. On my android test device, it connect to network without any proxy or firewall.

**Comment by kn100** [comment]
Can you show me what a response from your auth endpoint looks like for both a presence channel subscription and a private channel subscription?

Which server side library are you using?

**Comment by enginebai** [comment]
Is there any way to get the response from our auth endpoint from java SDK? Our backend is implemented in python SDK.

**Comment by kn100** [comment]
The easiest and least destructive approach might be to wireshark the connection or similar.

If it's easier, could you instead provide me with a minimal example of client code that encounters this issue? All it would need to do is connect and subscribe to a private channel!

**Comment by kn100** [comment]
@enginebai also have you seen https://github.com/pusher/pusher-websocket-java/issues/144

**Comment by kn100** [comment]
I'm going to close this as I believe everybody in this thread could benefit from reading through #144 - Specifically https://github.com/pusher/pusher-websocket-java/issues/144#issuecomment-433924613. Let me know if this does not help, and we can reopen the issue.
