### ISSUE TITLE
Reconnection again subscribe the channel  in private channel

### ISSUE THREAD

**Issue by Muhammadwahab** [pusher/pusher-websocket-java#229]
### What is the issue?

Hi i use pusher private channel in one of our android app it work good but when connection is lost the pusher again resubscribe the private channel which already subscribe at start. I think it should subscribe only once, when internet is lost or slow it should not be resubscribe again. I think you should look this suggestion for improvement of service

### Is it a crash report? Submit stack traces or anything that you think would help
this is improvement suggestion 
...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by benw-pusher** [comment]
The automatic resubscription to channels when the connection is restored is something many customers expect, and is actually a [documented feature](https://github.com/pusher/pusher-websocket-java#reconnecting) of our libraries. This isn't an enhancement we are likely to implement. 
You may be able to achieve the desired behaviour by monitoring for connection state changes and then ensuring the client [disconnects](https://support.pusher.com/hc/en-us/articles/4412239949969-How-Are-Concurrent-Connections-Counted-) entirely or [unsubscribes](https://pusher.com/docs/channels/using_channels/public-channels/#unsubscribe) from the necessary channels.
