### ISSUE TITLE
Pusher stops receiving events after a short period of time on a solid connection

### ISSUE THREAD

**Issue by xdansmith** [pusher/pusher-websocket-java#26]
I'm using the latest beta released and am finding that it is working, but after so many minutes of inactivity, the app quits firing onEvent(...) for the subscribed events. 

I'm monitoring onConnectionStateChange to log when the connection state changes and reconnect if it disconnects (because of the phone losing connectivity, etc), but this event is never firing. I can turn off WIFI on the phone to make sure the event is working, and then it will fire an event stating that it goes from connected to disconnected ([PusherService]/onConnectionStateChange(22024): Connection state changed from [CONNECTED] to [DISCONNECTED])

Is anyone else seeing this problem? 

Please let me know if there is any additional detail that I can provide to help reproduce this issue.

Thanks!

**Comment by MoustafaElsaghier** [comment]
it's too long but, any idea about setting pong time to 4h is effective or not, also, is that have any consequences for making time 4h? if not can I make it larger?
