### ISSUE TITLE
Changing host server is not working

### ISSUE THREAD

**Issue by yvesniyo** [pusher/pusher-websocket-java#268]
### What is the issue?

There is this library in laravel which called Beyondcode [https://github.com/beyondcode/laravel-websockets],
It does allow users to host their own Pusher, so I tried to connect this java websocket by changing the Host and proxy but nothing seems to work it does still send requests the default pusher server.
Is there anyway I can change that host to be my own server?

Actually I thinks it's not crash or any bug but again am beginner.

CC @pusher/mobile

**Comment by daniellevass** [comment]
Hi,

It's possible to specify the host as part of the [PusherOptions](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/PusherOptions.java).

You can see how to configure the PusherOptions in any of the example's e.g. [Public Channels Example](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/example/ExampleApp.java#L45).

Hope that helps,

Danielle.
