### ISSUE TITLE
"eventQueue" thread pool is not shutdown

### ISSUE THREAD

**Issue by mdpye** [pusher/pusher-websocket-java#27]
Currently we do not have a shutdown() method on the Pusher, and terminating the thread on disconnect is not correct either.
However, if we can't terminate the thread them the JVM will not quit.

This is probably being masked by Android's lifecycle management in most cases where it's in use (though I don't know where those threads are going, I hope they're being forcefully terminated eventually), but if the library were to be used in a traditional Java setting it would be a real pain.

**Comment by jhonjto** [comment]
is there a way for launch pusher with google play services and dont get the eventqueue error?
