### ISSUE TITLE
Please Add Release 2.2.2 to GitHub Release

### ISSUE THREAD

**Issue by hendrawd** [pusher/pusher-websocket-java#270]
### What is the issue?
Version 2.2.2 has been released a day ago, but the [GitHub release](https://github.com/pusher/pusher-websocket-java/releases) has not been updated yet, still version 2.2.1

### Is it a crash report? Submit stack traces or anything that you think would help
No

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by daniellevass** [comment]
Thanks for the reminder! Have updated the releases for [2.2.2](https://github.com/pusher/pusher-websocket-java/releases/tag/v2.2.2)
