### ISSUE TITLE
NoSuchMethodError Pusher 2.2.4 with Android 6

### ISSUE THREAD

**Issue by Jeff11** [pusher/pusher-websocket-java#283]
### What is the issue?
Version 2.2.4 produces lots of crashes with SSL on Android 6.0-6.0.1

### Is it a crash report? Submit stack traces or anything that you think would help

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
       at org.java_websocket.client.WebSocketClient.onSetSSLParameters(WebSocketClient.java:528)
       at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:475)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by Jeff11** [comment]
Android 5.1 is also affected. Same stack trace.

**Comment by daniellevass** [comment]
Hi,

Thanks for reporting. 

I've determined what the cause of the issue is and am working on a fix asap.

Will keep this issue updated with progress.

Thank you,

Danielle.
