### ISSUE TITLE
PusherEvent.getData always throwing ClassCastException 

### ISSUE THREAD

**Issue by reducedcarpet** [pusher/pusher-websocket-java#287]
Any time I try and get data out of a pusher event, I get the exception below. 

E/AndroidRuntime: FATAL EXCEPTION: pusher-java-client eventQueue
    Process: my.App, PID: 17419
    java.lang.ClassCastException: com.google.gson.internal.StringMap cannot be cast to java.lang.String
        at com.pusher.client.channel.PusherEvent.getData(PusherEvent.java:40)
        at my.Fragment$cacheListener$1.onEvent(myFragment.kt:43)
        at com.pusher.client.channel.impl.ChannelImpl$1.run(ChannelImpl.java:111)
        at com.pusher.client.util.Factory$1.run(Factory.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

For example (in kotlin) 

    val cacheListener = object : PrivateChannelEventListener {
        override fun onEvent(
            event: PusherEvent
        ) {
            println("DATA EVENT: " + event.data) 
}} 

Is enough to trigger it, I literally can't get the data to even print it, never mind try and use Gson on it. 

I can work around it with event.getProperty("data").toString() but it's annoying because .getData used to work. 

I should like to know why it is representing the internal data as a stringmap instead of it being a string? I don't have control over the input data, so what exactly is being fed in to get this issue? This has only recently started so I think it must be a data input issue. But it fully crashes my app which is glorious behaviour. 

I'm using 'com.pusher:pusher-java-client:2.2.1' for API target 30

CC @pusher/mobile

**Comment by rnstewart** [comment]
I'm running into this issue as well. It looks like it's blindly casting a Map into a String. Is this ever going to be fixed?

**Comment by sonologico** [comment]
The data field is expected to be a string. From which client and how are you sending the message that causes the issue?

**Comment by sonologico** [comment]
The `eventData` field is the entire event message. The `data` field that inside that map is what get when you call `getData`.

The `data` field is expected to be a string in general. That's what the documentation strongly suggests people to do and what the official SDKs do as far as I'm aware.

For your case, you can use `.get("data")` (instead of `.getData()`). That should give you an `Object` that you can cast accordingly.
