### ISSUE TITLE
OnEvent in Presence Channel doesn't fire

### ISSUE THREAD

**Issue by SaadSabry** [pusher/pusher-websocket-java#291]
Good day pusher team,

I'm using your library in my android app, and when hit my event in the presence channel, I don't receive any action in my onEvent method.

please noted that I connected successfully to pusher and subscribed to channel so please I have to know where is the problem.

                @Override
                public void onEvent(PusherEvent event) {
                    Log.e("EVENT_NAME", "" + event.getEventName());
                    finish();
                }
CC @pusher/mobile

**Comment by ben-pusher** [comment]
Hi! This is likely to be a configuration issue rather than a library issue - could I ask you to reach out to our support team at support@pusher.com? They will be able to work through the issue with you in detail.
