### ISSUE TITLE
ProGuard R8 Obfuscation not working in android app

### ISSUE THREAD

**Issue by lucasgv** [pusher/pusher-websocket-java#292]
When we enable the ProGuard obfuscation, Pusher stops receiving messages in the socket. The connection remains working, but the message does not go through.

We implement ProGuard R8 for security and performance purposes, therefore it cannot be disabled.
Testing occurs smoothly while ProGuard and R8 are disabled.

We do not get crashes or errors reports. It just stops receiving event messages from Pusher.

Are there any rules we could use to partially disable ProGuard in order to not enabling Pusher SDK obfuscation?

Are there any Pusher library updates which could work well along with obfuscation?

We've tried to use the following code unsuccessfully:
-keep class .com.pusher.* {* ; }
-keep interface com.pusher.* { *; }
-keep class com.pusher.client.connection.ConnectionState { *; }
-keep class com.pusher.client.connection.ConnectionStateChange { *; }

Thanks.
Regards.

**Comment by ccaseypusher** [comment]
Have you tried the following keep rule - 

-keep class com.pusher.** { *; }

**Comment by lucasgv** [comment]
We tried but not works. We are searching for more details to help.

**Comment by lucasgv** [comment]
We found a way to resolve it, the problem is on the model when receiving the message from Pusher with obfuscation, so we just put an annotation to make the map works.

Thanks a lot, now is working fine.

Regards!!
