### ISSUE TITLE
java.lang.NoClassDefFoundError: com/pusher/client/Authorizer

### ISSUE THREAD

**Issue by mProjectsCode** [pusher/pusher-websocket-java#293]
### What is the issue?
`java.lang.NoClassDefFoundError: com/pusher/client/Authorizer`
I get this error when building my Java project.

The only code that makes sense to throw this error is this part:

HashMap<String, String> headers = new HashMap<String, String>();
headers.put("Authorization", sessionToken);

HttpAuthorizer authorizer = new HttpAuthorizer(StreamSniperMinecraft.authEndpoint);
authorizer.setHeaders(headers);

 PusherOptions options = new PusherOptions()
        .setHost(StreamSniperMinecraft.pusherEndpoint)
        .setWsPort(443)
        .setUseTLS(true)
        .setAuthorizer(authorizer);

Because the `HttpAuthorizer` is the only class that implements `com.pusher.client.Authorizer`.
... 

### Is it a crash report? Submit stack traces or anything that you think would help

Caused by: java.lang.ClassNotFoundException: com.pusher.client.Authorizer
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(Unknown Source)
...

---- 

CC @pusher/mobile

**Comment by samita-acharya** [comment]
Hi, this seems like something Support can assist with. Please send an email to support@pusher.com.

**Comment by samita-acharya** [comment]
Hi @mProjectsCode, this seems like something Support can assist with. Please send an email to support@pusher.com.
