### ISSUE TITLE
Automatically disconnects after 30 seconds

### ISSUE THREAD

**Issue by ljh0326** [pusher/pusher-websocket-java#294]
### What is the issue?
Automatically disconnects after 30 seconds
How can I connect all day?
![image](https://user-images.githubusercontent.com/17944004/102212565-c6159400-3f18-11eb-8d50-56f3119fcf5a.png)

I have set PongTimeout and MaxReconnectGapInSeconds.
![image](https://user-images.githubusercontent.com/17944004/102213171-b0ed3500-3f19-11eb-8952-b05e2478a6ef.png)

help plz
... 
### Is it a crash report? Submit stack traces or anything that you think would help
...
### Any improvements you suggest
...
---- 

CC @pusher/mobile

**Comment by samita-acharya** [comment]
Hi @ljh0326, you're experiencing this as you have enabled authorised connections. I have addressed this in the ticket you raised(https://pusher.zendesk.com/agent/tickets/23728). As such, I will close this issue. If you have any further questions, please reply to the ticket.

**Comment by ljh0326** [comment]
Thanks a lot
