### ISSUE TITLE
java.lang.IllegalArgumentException: Channel name private-user.13.25 is invalid. Private channel names must start with "private-" and presence channel names must start with "presence-"

### ISSUE THREAD

**Issue by willBars** [pusher/pusher-websocket-java#298]
i use PrivateEncryptedChannel model,and socket connnect success,but subscribe failed,

java.lang.IllegalArgumentException: Channel name private-user.13.25 is invalid. Private channel names must start with "private-" and presence channel names must start with "presence-"

please call me resson

**Comment by benw-pusher** [comment]
I believe you will need to ensure the typing is correct. For example, I experience the same error with the following: 

`val privateUserChannel = pusher.subscribePrivate("private-user.13.25"...`

however when using 
`val privateUserChannel: PrivateChannel = pusher.subscribePrivate("private-user.13.25".... `

The error is not present. 
Let me know if this helps.

**Comment by benw-pusher** [comment]
I haven't had a response here so I will close this out - feel free to reopen if you need additional assistance.
