### ISSUE TITLE
How to use authorizer.authorize() ?

### ISSUE THREAD

**Issue by sebasdeweert** [pusher/pusher-websocket-java#316]
### What is the issue?
I want to implement Pusher in my Android app. I checked the README section about setting the `Authorizer` and I get `CONNECTED` from the `onConnectionStateChange` function.

So far so good. Now I want to authenticate with my own server to subscribe to some private channels.

In iOS I use the `AuthRequestBuilder` when setting my options:
 
```
func connectToWebSocket() {
        let options = PusherClientOptions(authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: AuthRequestBuilder()), host: .cluster("eu"))
        
        pusher = Pusher(key: "***", options:options)
       
        pusher.delegate = self
        pusher.connect()
}

class AuthRequestBuilder: AuthRequestBuilderProtocol {
    func requestFor(socketID: String, channelName: String) -> URLRequest? {
        if let accessToken = UserDefaultsManager.accessToken {
            var request = URLRequest.init(url: URL(string: "https://***.com/pusher/channels_auth")!)
            request.httpMethod = "POST"
            request.httpBody = "socket_id=\(socketID)&channel_name=\(channelName)".data(using: String.Encoding.utf8)
            request.addValue("Bearer " + accessToken, forHTTPHeaderField: "Authorization")
            return request
        }
        return nil
    }
}
```

Unfortunately with this Java library the implementation is not working for me. I figured out that I have to call the `authorizer.authorize()` function and fill in my `channelName` and `socketId`. When do I need to do this? I only have a `socketId` after connecting to pusher. 

Also when I try to do this after `ConnectionState.CONNECTED` I get the following error:  `FATAL EXCEPTION: pusher-java-client eventQueue`

```
class SocketManager {

    private var pusher: Pusher? = null

    fun connectToWebsocket(accessToken: String, userId: String) {
        val authorizer = HttpAuthorizer("https://***.com/pusher/channels_auth")

        val headers: MutableMap<String, String> = HashMap()
        headers["Authorization"] = "Bearer $accessToken"
        headers["Accept"] = "application/json"
        authorizer.setHeaders(headers)

        val options = PusherOptions()
        options.authorizer = authorizer
        options.setCluster("eu")

        pusher = Pusher("***", options)

        pusher?.connect(object : ConnectionEventListener {
            override fun onConnectionStateChange(change: ConnectionStateChange?) {
                if (change?.currentState == ConnectionState.CONNECTED) {

                    -----------
                    SHOULD I IMPLEMENT authorizer.authorize() HERE?         
                    // authorizer.authorize("user.$userId", pusher?.connection?.socketId)
                    -----------    

                }
            }

            override fun onError(message: String?, code: String?, e: Exception?) {
                println("There was a problem connecting! code ($code), message ($message), exception($e)")
            }
        })


    }
```

Im using the latest version: 2.2.8
...

### Any improvements you suggest
Maybe update the README how to use `authorizer.authorize()` when you want to use your own server for connecting to private channels.
...

---- 

CC @pusher/mobile

**Comment by sonologico** [comment]
If you're using the `HttpAuthorizer`, you don't need to call the `authorize` method yourself. You don't need to do anything on connection. The authorization happens per channel. The library itself will do a call to the authorization endpoint you provided to the `HttpAuthorizer` every time you try to subscribe to a private channel.

There's an example app using private channels here: [](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/example/PrivateChannelExampleApp.java)

**Comment by sebasdeweert** [comment]
Thank you for your reply. I was not aware of the Example app. Guess I was to fast with asking the question. It's working now 😄 .
