### ISSUE TITLE
Presence Channel Android Bug

### ISSUE THREAD

**Issue by mannea94** [pusher/pusher-websocket-java#317]
I have a problem with frequently disconnecting/reconnecting Pusher, specifically with the Presence Channel. It is a Chat Screen between two people only, and in the background is connected the PrivateChannel that receives events and the PresenceChannel which has the appropriate listeners: onUsersInformationReceived, userSubscribed, userUnsubscribed, onSubscriptionSucceeded, etc. With the help of this channel PresenceChannel I receive the system message for the user whether he entered the Chat or left it. I do not know why I get an event in PrivateChannel that the user left the chat, so in PresenceChannel in onUsersInformationReceived I get that two users are currently in Chat, then in onSubscriptionSucceeded I get a successful subscription again and next I get an event that the user has entered the chat. More precisly [the name of the user] has left the visit, [the name of the user]  has joined the visit. This scenario happens very often. Is there a solution to this problem, can a more stable pusher connection be made to avoid persistent successful subscription in PresenceChannel?

**Comment by benw-pusher** [comment]
You have reached out to us at Pusher Support for assistance with this. I will close the thread here and continue to assist you via Support.
