### ISSUE TITLE
Invalid response from Authorizer: no user_id key in channel_data object: null

### ISSUE THREAD

**Issue by usman-khawar** [pusher/pusher-websocket-java#318]
### What is the issue?

When connecting to the pusher using authorizer. I'm getting this error. There is no way of sending user_id in the authorizer. 

 val authorizer =
            HttpAuthorizer(
                PUSHER_AUTH_URL, UrlEncodedConnectionFactory(
                    mapOf(
                        "Accept" to "application/json",
                        "Authorization" to "Bearer $token",
                    )
                )
            )

 val options = PusherOptions().setAuthorizer(authorizer)
        options.isUseTLS = true
        mPusherInstance = Pusher(PUSHER_API_KEY,
            options
        )

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by benjamin-tang-pusher** [comment]
I will give you an example of how to do this shortly.

**Comment by benjamin-tang-pusher** [comment]
That error message is because of an incorrect response from your server (such as wrong authenticate() method) . Can you paste your server's auth code here?

As a general FYI, in my Java server I did:

```
@PostMapping("/presence_auth")
	public String presenceAuth(@RequestParam(value = "socket_id") String socketId,
			@RequestParam(value = "channel_name") String channel) {

		String userId = "unique_user_id";
		Map<String, String> userInfo = new HashMap<>();
		userInfo.put("name", "my name");
		userInfo.put("twitterId", "@leggetter");

		String authBody = pusher.authenticate(socketId, channel, new PresenceUser(userId, userInfo));

		return authBody;
	}
}
```

You client should get the response described here: https://pusher.com/docs/channels/library_auth_reference/auth-signatures/#presence-channels

**Comment by benw-pusher** [comment]
no response, closing.
