### ISSUE TITLE
Authorizer with Secret key

### ISSUE THREAD

**Issue by daliborristic883** [pusher/pusher-websocket-java#319]
### What is the issue?
Now I am using this library and iOS working perfectly.
iOS SDK provides OCAuthMethod with Secret key.

`let authMethod = OCAuthMethod.init(secret: secretKey)
let host = OCPusherHost(cluster: Constants.SocketKeys.cluster)
let options = PusherClientOptions(ocAuthMethod: authMethod, autoReconnect: true, ocHost: host, port: nil, useTLS: true, activityTimeout: nil)`

But I can't see similar method on Android library.

Is there any way to make authorise with Secret key instead endpoint?

Thank you.
Dalibor
... 

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by benjamin-tang-pusher** [comment]
Hi, we don't have a method for authenticating with the secret key instead of endpoint. 

Its in the Swift iOS library mainly for development purposes, having the secret key on the client generally isn't recommended
