### ISSUE TITLE
Significant Battery Drain in Densely Populated Areas

### ISSUE THREAD

**Issue by ammurdoch** [pusher/pusher-websocket-java#322]
### What is the issue?

We are developing a wearable Android device and using Pusher Channels to send messages to those devices.  We have noticed significant battery drain on our Android devices in certain environments.  Most of the time, we don't have any problems, but in one densely populated area in particular, we've seen 10x battery drain when the Pusher client has been initiated and has an open websocket.

Is this an issue you are aware of?  How can get more insight into what's going on?  How can we fix this?
... 

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by benjamin-tang-pusher** [comment]
This was dealt with by Pusher support separately, so I will close this.
