### ISSUE TITLE
Pusher disconnects after few days of connection

### ISSUE THREAD

**Issue by avaranovich** [pusher/pusher-websocket-java#34]
As a part of my server-side technology, I need to keep pusher client connected for a very long time, weeks and months. After some time, hovewer, I see this in my server log "Please reconnect immediately ; code: 4200"

Shouldn't this be handled by the library? Otherwise what is the best practice here? Should I handle this error and reconnect manually?

From the pusher protocol description, this is quite generic error, and does not provide any details (I presume the issue is not in my code).

**Comment by vchatterji** [comment]
It would be good if pusher provides a tested code sample of implementing the pusher service in a background service in Android with PARTIAL_WAKE_LOCK and automatic reconnection. This would be really helpful for developers.

Ideally the code sample should handle connectivity events like network switching from wifi to mobile data or loss of signal entirely and reconnection.

What I'm looking for is a bullet proof, always on, 100% reliable connection. Battery life is not that important in my use case as the phone will always be connected to power.
