### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError [ com.pusher.client.Pusher$$ExternalSyntheticLambda0 ]

### ISSUE THREAD

**Issue by gmg-avid** [pusher/pusher-websocket-java#352]
What is the issue?
Fatal Exception: java.lang.NoClassDefFoundError [ com.pusher.client.Pusher$$ExternalSyntheticLambda0 ]

The above fatal exception occurred to our users when we initialized the pusher web stocket. This issue occurs on android versions 5.1.1 & 6.0.1 and 83% of issues occur on Nexus 5x devices, Please check the below screenshot. Could you please suggest us solution to resolve this problem?

<img width="412" alt="Screenshot 2022-11-29 at 10 41 20 AM" src="https://user-images.githubusercontent.com/77985558/204444754-bbbf6782-e3c2-46d7-a508-ac1f18686f6f.png">

<img width="404" alt="Screenshot 2022-11-29 at 10 41 38 AM" src="https://user-images.githubusercontent.com/77985558/204444896-174fd586-396a-45ff-9a6a-9c9384e39da6.png">

Pusher Version that using in our application - implementation 'com.pusher:pusher-java-client:2.4.4'

Is it a crash report? Submit stack traces or anything that you think would help
Fatal Exception: java.lang.NoClassDefFoundError [ com.pusher.client.Pusher$$ExternalSyntheticLambda0 ]
com.pusher.client.Pusher. (Pusher.java:103)
com.pusher.client.Pusher. (Pusher.java:85)
com.nmbl.app.pusher_web_socket.SBPusherWebSocket.setPusherSocketOptions (SBPusherWebSocket.java:86)
com.nmbl.app.pusher_web_socket.SBPusherWebSocket.getInstance (SBPusherWebSocket.java:38)
com.nmbl.app.app_versioning.manager.SBApiManager.getAuthorizationRequest (SBApiManager.java:364)
com.nmbl.app.app_versioning.manager.SBApiManager.lambda$generateOkHttpClient$0 (SBApiManager.java:302)
com.nmbl.app.app_versioning.manager.SBApiManager$$InternalSyntheticLambda$0$b9d2545deb1640be22e069dd0fb10db3adab27333d202ada33a968fda8976bee$0.intercept$bridge (SBApiManager.java:1)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)

Please check the screenshot of the stack trace

[https://mallowtechno-my.sharepoint.com/:i:/g/personal/gowtham_muralivel_mallow-tech_com/EbzF55o2Da9CrBPkEjuWGTEBa3mvVppIK1dLOvSyT8kYzw?e=2oZWvd](https://github.com/pusher/pusher-websocket-java/issues/url)
CC @pusher/mobile

**Comment by benw-pusher** [comment]
Android versions 5 and 6 will require desugaring, see https://developer.android.com/studio/write/java8-support#library-desugaring for more information on how to implement this. 
This requirement is detailed in the [supported platforms](https://github.com/pusher/pusher-websocket-java#supported-platforms) of the library.

**Comment by benw-pusher** [comment]
I'll close this as we haven't had a response, feel free to raise a ticket with us at https://support.pusher.com/hc/en-us if you need further assistance.

**Comment by Yoko999** [comment]
Have the same issue on Android 5-6, link didn't help. Tried various versions of desugar_jdk_libs.

App's Target SDK 33
Pusher implementation 'com.pusher:pusher-java-client:2.4.4'

@gmg-avid, how did you resolved it?

**Comment by dharmeshgigs** [comment]
Crashing with version 2.2.8 on API level 23.
