### ISSUE TITLE
An exception is getting thrown by the application and failing to connect to the websocket service

### ISSUE THREAD

**Issue by lincontroy** [pusher/pusher-websocket-java#354]
###W/User: An exception was thrown by the websocket
I/System.out: There was a problem connecting!
... 

###This is not a crash report but something i see as a potential bug

...

###Check on the issue

...

---- 

CC @pusher/mobile

**Comment by benw-pusher** [comment]
Can you share a bit more about this issue, for example when does this error get thrown?
Is it always encountered, or does it happen under certain circumstances?
What is the code you are using to create the connection?

**Comment by benw-pusher** [comment]
We haven't had a response here so will close out. If you need further support please contact us at https://support.pusher.com/hc/en-us/requests/new
