### ISSUE TITLE
compression?

### ISSUE THREAD

**Issue by goodale** [pusher/pusher-websocket-java#363]
### What is the issue?

this library accepts a POJO and will marshal it to JSON without needing Jackson, etc.   however,  using this library's native marshalling means there is no way to pre-compress the JSON.   But there is also not a way to tell pusher to compress the payload so we can take advantage of the full 10kb limit.

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

If it is already supported, document how compression works.  Alternatively, update the library to allow gzipping the JSON that is sent to the channel clients.  Brower's universally support gzip'd data so this seems like a reasonable request.

---- 

CC @pusher/mobile

**Comment by benw-pusher** [comment]
I have shared the feedback with the team, however we can't commit to any release for this at this time.
