### ISSUE TITLE
Parameter NullPointerException in Public channel configuration.

### ISSUE THREAD

**Issue by RedwanSharafatKabir** [pusher/pusher-websocket-java#365]
I am trying to connect a public channel with cluster, host, port and app-key. But after connecting the pusher and subscribe, I am getting this error. Why is this issue occurring and how to solve it?

FATAL EXCEPTION: pusher-java-client eventQueueProcess: [app_package_name], PID: 9184
java.lang.NullPointerException: Parameter specified as non-null is null: method
[app_package_name].utils.servicesNotification.PusherDataReceiverService$managePusherReceiver$2.onError, parameter code at [app_package_name].utils.servicesNotification.PusherDataReceiverService$managePusherReceiver$2.onError(Unknown Source:13)

**Comment by benw-pusher** [comment]
To be able to investigate we will need to review your code, along with the full stack trace and a description of when this error is encountered (upon subscribe, reconnect, event received etc).

**Comment by RedwanSharafatKabir** [comment]
I am trying this in Kotlin. Here this the code -

`var channel: Channel?= null

        try {
            val options = PusherOptions()
            options.setCluster("cluster")
            options.isUseTLS = false
            options.setHost("152.259.125.44")
            options.setWsPort(6001)

            val pusher = Pusher("app-key", options)

            pusher.connect(object : ConnectionEventListener {
                override fun onConnectionStateChange(change: ConnectionStateChange) {
                    Log.i("pusher_state_change", "State changed from ${change.previousState} to ${change.currentState}")
                }

                override fun onError(message: String?, code: String?, e: Exception?) {
                    try {
                        if (code != null) {
                            Log.i("pusher_state_error", "There was a problem connecting! code ($code), message ($message), exception(${e!!.message})")
                        } else {
                            Log.i("pusher_state_error", "Error received without a code! message ($message), exception(${e!!.message})")
                        }

                    } catch (e: Exception) {
                        Log.i("pusher_state_error", "Error received without a code! message ($message), exception(${e.message})")
                    }
                }

            }, ConnectionState.ALL)

            try {
                channel = pusher.subscribe("channel-name")

            } catch (e: Exception) {
                Log.i("pusher_exception", e.message.toString())
            }

        } catch (e: Exception) {
            Log.i("pusher_exception", e.message.toString())
        }`

**Comment by benw-pusher** [comment]
I can see you are connecting to a custom host. We aren't able to support non-Pusher websocket services. 
You may also need to check that some of the values error values are not null, for example the message.

**Comment by RedwanSharafatKabir** [comment]
Actually I am receiving data from another pusher websocket service built in Node.js. Also checking the nul value of message.
Also getting real-time data frequently. But after sometime it gives this error and app crashes.
