### ISSUE TITLE
Why embed Java-Websockets?

### ISSUE THREAD

**Issue by timmolter** [pusher/pusher-websocket-java#38]
Just curious. It is causing a classpath issue for me to have both jars in use in the same Android project. Is it because they're not releasing a version with needed functionality?

**Comment by mdpye** [comment]
It's been a while, but this should have been resolved, we now pull Java-Websockets from the clojars repo where a recent version is available.

**Comment by timmolter** [comment]
Interesting. Who put the websocket jar on clojars?

**Comment by mdpye** [comment]
A third party, @jasminsehic in response to https://github.com/TooTallNate/Java-WebSocket/issues/252

**Comment by mdpye** [comment]
Possible because on a new repo the org.java-websockets group wasn't taken yet. They offered to make the project owner an admin afterwards in the PR.

**Comment by timmolter** [comment]
That's a different approach! Thanks for the info.
