### ISSUE TITLE
Gradle-ify the project

### ISSUE THREAD

**Issue by leggetter** [pusher/pusher-websocket-java#55]
- [ ] Update project to use Gradle (build, test etc.)
- [ ] Create IDE project files
- [ ] Simple deployment to package registry
- [ ] Improve "Getting Started" README with gradle details
- [ ] Improve "Library Development Environment" README details

Also see #53

**Comment by mdpye** [comment]
> Create IDE project files

I've generally found that project definition, local config and personal prefs all tend to be commingled by the IDEs. Usually the correct approach is to leave them out of the repo and let people generate them when importing the project.

For example, maven has a plugin which can generate eclipse projects, or eclipse has a module that can import maven projects. IntelliJ can generate its project config directly from a maven project: https://www.jetbrains.com/idea/help/maven.html (under "Import of maven projects")

The same should be true of gradle, if it hopes to be the one-true-build-system.

**Comment by AlexBravo** [comment]
Considering how many Android developers use Gradle, it's probably a good idea to give it a better support.

**Comment by trevorrjohn** [comment]
I think the support is there, it is now listed in the readme about how to include it in your gradle file. Not sure what else could be done here.
