### ISSUE TITLE
mvn dependency is not loaded in project

### ISSUE THREAD

**Issue by atinderiotasol** [pusher/pusher-websocket-java#60]
When i add the maven dependency in projects pom file, it is not able to download the required jar.

**Comment by mdpye** [comment]
Which jar is the problem?

**Comment by atinderiotasol** [comment]
I was trying to add the following maven dependency . But its throwing exception can not read jar file 
<dependency> 
<groupId>com.pusher</groupId>
<artifactId>pusher-rest-java</artifactId> 
<version>0.9.0</version>
 </dependency>

**Comment by mdpye** [comment]
OK, then the issue should most likely be filed against https://github.com/pusher/pusher-rest-java, this is the repo for a different library. Please open an issue there and include the error from your maven run.
