### ISSUE TITLE
Dependency error with java-websocket

### ISSUE THREAD

**Issue by tjohn** [pusher/pusher-websocket-java#63]
I am trying to add this library to my Android app using Gradle, but I am encountering this error:

```
$ ./gradlew app:dependencies

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find org.java-websocket:java-websocket:1.3.1.
     Searched in the following locations:
         https://jcenter.bintray.com/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.pom
         https://jcenter.bintray.com/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.jar
         file:/usr/local/opt/android-sdk/extras/android/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.pom
         file:/usr/local/opt/android-sdk/extras/android/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.jar
         file:/usr/local/opt/android-sdk/extras/google/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.pom
         file:/usr/local/opt/android-sdk/extras/google/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.jar
     Required by:
         MyApplication:app:unspecified > com.pusher:pusher-java-client:0.3.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.15 secs
```

Pretty basic here, this is with a new app. I looked on maven.org and there is no java-websocket version 1.3.1. There is a version 1.3.0, but I am not sure how this is working for anyone at the moment.

Here is my sample app:

https://github.com/tjohn/pusher

**Comment by mdpye** [comment]
Hi @tjohn. The correct version of the java websocket lib is only available from the clojars repo, you might need to add it to your gradle file. I'm not sure why this is not working automatically for gradle, the details of the repo are in the pom, and mvn would read this and check the repository: https://github.com/pusher/pusher-websocket-java/blob/master/pom.xml#L66-L71

If you know how to get this to work automatically by distributing something gradle understands, that would be great!

**Comment by tjohn** [comment]
Ah, ok. Here is the code needed then:

```gradle
repositories {
    maven { url 'http://clojars.org/repo' }
}
```

**Comment by tjohn** [comment]
I have created created
https://github.com/pusher/pusher-websocket-java/pull/64 for future Gradle
users.


Trevor John

**Comment by arlindiDev** [comment]
@trevorrjohn thank you that worked :)
