### ISSUE TITLE
AuthenticationFailure for private channel subscription

### ISSUE THREAD

**Issue by macin11** [pusher/pusher-websocket-java#65]
On subscribing to private channel I get this very error every time.
Authentication failure due to [{"auth":"f1cec20bd1a33b264fe5:06a34c74fc7550ce11f68a466a312c4e3f1239cdbf91db5b4a605136f3df1e25"}], exception was [com.pusher.client.AuthorizationFailureException: {"auth":"f1cec20bd1a33b264fe5:06a34c74fc7550ce11f68a466a312c4e3f1239cdbf91db5b4a605136f3df1e25"}]
Currently I am using pusher.0.3.3.jar version.Is android OS version has to do anything with pusher  jar version as previously I was using pusher-java-client-0.0.1-SNAPSHOT-jar-with-dependencies.jar which was working fine upto android api level 19.

**Comment by leggetter** [comment]
This means that the auth endpoint you have defined is either not returning a 200 response or another IO type exception is occurring when interacting with your auth endpoint. See: https://github.com/pusher/pusher-websocket-java/blob/fdb4ad227a62f6c5e73f37222c5a0747f0464b6e/src/main/java/com/pusher/client/util/HttpAuthorizer.java#L140-L149

I'd recommend checking your auth endpoint server logs as the first port of call. You should also be able to get additional information by inspecting the exception - based on the output being an auth JSON blog it could simply be that the HTTP response isn't 200.

Please let me know how you get on.

**Comment by macin11** [comment]
The problem was at endpoint.Thnaks for  your response
