### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by leggetter** [pusher/pusher-websocket-java#67]
Should include:

* A solution to #66 
* A merge of #57 which resolves #55 

Work will take place in https://github.com/pusher/pusher-websocket-java/tree/0.4.0-release

**Comment by leggetter** [comment]
https://github.com/pusher/pusher-websocket-java/commit/0eaa1fd3205747ee50c9ca65f5059f94b11e124f introduces a `Pusher.getChannel(String channelName);` that returns the `Channel` with the given name if it has been subscribed to and `null` if the Channel has not been subscribed to.

It doesn't offer a `true`/`false` return value, but whether a Channel has been subscribed to can easily be checked via:

```java
if(pusher.getChannel('check-channel') == null) {
  // Channel has not been subscribed to
}
else {
  // Channel HAS been subscribed to
}
```

Is this satisfactory, or would people also like something like an `Boolean isSubscribe(String channelName)` helper method?

**Comment by leggetter** [comment]
@mdpye - any thoughts on this?

**Comment by mdpye** [comment]
Returning the `Channel` gives people the option to bind and unbind events on the channel, which they might find useful. However, this method signature can only return the lowest common denominator `Channel` interface, not the private or presence variants which have additional functionality.

Because of that limitation, I might be inclined not to return the channel, but *only* to provide the `boolean` signature.

Almost unrelated, but I notice that commit has a fair mix of tabs and spaces, could you fix your editor please? We only ever use spaces, and 4 is the standard for Java projects.

**Comment by leggetter** [comment]
> Because of that limitation, I might be inclined not to return the channel, but only to provide the boolean signature.

I know casting is naughty :imp:, but if you're explicitly getting a private or presence channel (seen via name prefix) on the exact same line as the cast is it really that bad?

```java
PrivateChannel retrievedChannel = (PrivateChannel) pusher.getChannel("private-channel");
```

More than happy to be sent away to read some docs or blog post here.

We could create specific types `get` methods e.g. `getChannel`, `getPrivateChannel` and `getPresenceChannel`?

@ruckus @macin11 @rmujica @mwaclawek @crossle - please provide your input if you've still an opinion on all of the above.

> Almost unrelated, but I notice that commit has a fair mix of tabs and spaces, could you fix your editor please? We only ever use spaces, and 4 is the standard for Java projects.

Eclipse Luna :heart_eyes:. I'll look at fixing.

**Comment by mdpye** [comment]
Lack of type-safety (in the interface especially, what about when it changes?) is undesirable, so I'd avoid it unless I could come up with a strong argument describing why it's necessary.
As far as I've seen, the argument thus far is "I was exposing something (whether a channel is subscribed) and thought it might be convenient to expose more (the `Channel` object)", which is a bit soft to allow casts in to the external interface IMO.

**Comment by trevorrjohn** [comment]
@mdpye as a client to the api it would be nice for me not to have to manage the channel objects. I have written a lot of code around checking if I already have a channel for a specific event. I am not sure what the right solution would be here, I agree the casting idea is not great and have different getters for the underlying channel implementations also feels dirty. What would be nice is if the channel interface was the same for all implementations, and were either no-ops for methods that they don't actually implement or threw exceptions. This might also mean that the interfaces might have more methods to check what you could do with specific instances for example `Channel#canSubscribeToPrivate...`.
