### ISSUE TITLE
Pusher.unsubscribe(String channelName) is painfully slow

### ISSUE THREAD

**Issue by roccozanni** [pusher/pusher-websocket-java#70]
Unsubscribing from a channel is executed immediately and not using the event queue, like for example in `Pusher.subscribe(String channelName)`. Because the unsubscribe message is generated using Gson this is painfully slow on Android when executed in the main thread.

On budget phones it takes 15-30ms just for generating the json message, causing the main thread to block and this leads to frame rate drop and animations lag.

**Comment by zimbatm** [comment]
Hi @roccozanni , thanks a lot for sharing your use-case.

You're making a good point. In the mean time wouldn't it be possible to put the whole pusher lib on a separate thread from the UI ?

**Comment by roccozanni** [comment]
Hi,
thanks for getting back to me, offloading the main thread it's exactly what I did right now.

In terms of API, i think this is an issue to solve because usually if an object it's safe to use in the main thread, all it's public methods should be safe. In this case some methods are safe, some other methods aren't.

**Comment by leggetter** [comment]
:+1: definitely something we should fix.

**Comment by zimbatm** [comment]
Yeah agreed, we should fix that.

**Comment by mdpye** [comment]
Do you have any more details about the hardware affected and any data which can demonstrate that it is due to the json generation? I know Gson is comparatively slow due to the heavy use of reflection, but 15-30ms is extraordinary for such a small object.

**Comment by leggetter** [comment]
> Unsubscribing from a channel is executed immediately and not using the event queue

@mdpye - It seems a reasonable suggestion for the library to use the event queue. So we don't need @roccozanni to do any additional work for us here. He's also already got a workaround.

**Comment by jpatel531** [comment]
Closing for now as #74 has been merged
