### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by jpatel531** [pusher/pusher-websocket-java#80]
```
* What went wrong:
Execution failed for task ':uploadArchives'.
> Could not publish configuration 'archives'
   > A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact pusher-java-client:jar:jar:null, trying to add MavenArtifact pusher-java-client:jar:jar:null.
```

In `pom.xml`, I have:

```xml
    <version>1.0.0-SNAPSHOT</version>
```

The credentials are in `.gradle/gradle.properties`

**Comment by leggetter** [comment]
@andyberry88 - any pointers on this one? If it's going to be a tricky one maybe we can look at this if we catch up late next week?

**Comment by andyberry88** [comment]
@leggetter Looks like the tasks that were generating archives were missing the `classifier` config. This is added by #81 (you may want to change the classifiers, I've gone with what was in https://repo1.maven.org/maven2/com/pusher/pusher-java-client/0.3.3/).
