### ISSUE TITLE
1.0.0 appears to be unavailable on maven central

### ISSUE THREAD

**Issue by markljones** [pusher/pusher-websocket-java#82]
The 1.0.0 README says to put 1.0.0 in my gradle dependencies section, but when I build, the jar can't be found ("Failed to resolve com.pusher:pusher-java-client:1.0.0").

The link in the README below that says I can get the jars directly from http://repo1.maven.org/maven2/com/pusher/pusher-java-client/ but the highest I see there is 0.3.3.

What gives?

**Comment by leggetter** [comment]
1.0.0 hasn't been fully released yet. We'll update you as soon as it has.

**Comment by jpatel531** [comment]
@markljones thanks for getting in touch - this was released yesterday afternoon

**Comment by markljones** [comment]
@jpatel531 thanks, sorry for the noise

**Comment by jpatel531** [comment]
no problem! :)
