### ISSUE TITLE
Maven dependency java-websocket

### ISSUE THREAD

**Issue by james-turner** [pusher/pusher-websocket-java#83]
According to the pom.xml you seem to rely on java-websocket library 1.3.1, however according to maven (http://mvnrepository.com/artifact/org.java-websocket/Java-WebSocket and http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22Java-WebSocket%22) there is no such version.

    <dependency>
         <groupId>org.java-websocket</groupId>
         <artifactId>java-websocket</artifactId>
         <version>1.3.1</version>
    </dependency>

Suggest downgrading to 1.3.0 instead so that dependencies resolve correctly.

**Comment by leggetter** [comment]
The dependency is in http://clojars.org:
https://clojars.org/org.java-websocket/java-websocket

The README needs updating to reflect the requirement for another repository.

**Comment by hamchapman** [comment]
I think it's already there:

https://github.com/pusher/pusher-websocket-java#gradle

**Comment by leggetter** [comment]
@hamchapman @jpatel531 - but what about folks that aren't using Gradle? Say they're only using Maven, what tells Maven to fetch the java-websocket dependency from `clojars.org`?

**Comment by jpatel531** [comment]
Yeah I think one has to add 

```xml
    <repositories>
        <repository>
            <id>clojars.org</id>
            <url>http://clojars.org/repo</url>
        </repository>
    </repositories>
```

**Comment by jpatel531** [comment]
i'll add to the readme

**Comment by mdpye** [comment]
Hmm. I was under the impression that https://github.com/pusher/pusher-websocket-java/blob/master/pom.xml#L66-L71 covered it, but perhaps that's only when building the lib, not building with the lib as a dependency.

**Comment by leggetter** [comment]
We thought that too. But @jpatel531 did some testing around it.

**Comment by mdpye** [comment]
Hmm. I wouldn't have been so keen on using the clojars repo as a work around for not being able to get the author to push a new release to maven central repo if I'd know that. Sorry all.
