### ISSUE TITLE
Automatic reconnection

### ISSUE THREAD

**Issue by jd-alexander** [pusher/pusher-websocket-java#89]
Does the library have automatic reconnection built in with support for network change events via say a broadcast receiver?

**Comment by jpatel531** [comment]
@leggetter @mdpye : 

The best way to automatically reconnect would be to use Android's `ConnectivityManager`. But - say - if people should wish to use the library in a non-Android environment, how could we make such a change compatible? A separate Android-specific build? I'm not too experienced in this, so I wonder about the best way forward..

**Comment by kn100** [comment]
Closing due to age
