### ISSUE TITLE
onEvent not fired

### ISSUE THREAD

**Issue by lalon** [pusher/pusher-websocket-java#92]
I'm using pusher-java-client 1.0.2 (tried the same with 1.0.0, 0.3.3, 0.3.0, 0.2.1).
The android client subscribes to a channel, but events are not fired(onEvent not called).
While in my js client events do fire up for the same events.

```
// Create a new Pusher instance
mPusher = new Pusher(Defines.PUSHER_APP_KEY);

mPusher.connect(new ConnectionEventListener() {
    @Override
    public void onConnectionStateChange(ConnectionStateChange change) {
        Logger.i("pusher: State changed to " + change.getCurrentState() +
                " from " + change.getPreviousState());
    }

    @Override
    public void onError(String message, String code, Exception e) {
        Logger.e("pusher: There was a problem connecting! msg:" + message);
    }
}, ConnectionState.ALL);

Channel channel = mPusher.subscribe("test_chan", new ChannelEventListener() {
    @Override
    public void onSubscriptionSucceeded(String channel) {
        Logger.i("pusher: subscribed");
    }

    @Override
    public void onEvent(String channel, String event, String data) {
        Logger.i("pusher: channel=" + channel + " event=" + " data=" + data);
    }
}, "test_event");
```

output log after sending some events:

01-03 15:47:02.884 pusher: State changed to CONNECTING from DISCONNECTED

01-03 15:47:04.403 pusher: State changed to CONNECTED from CONNECTING

01-03 15:47:04.709 pusher: subscribed

What could be the reason my onEvent callback is not fired when publishing a "test_event" in "test_chan"?

**Comment by sham3k** [comment]
+1

**Comment by carueda** [comment]
Wow, not reply at all in almost a year!  `: (`

**Comment by dustije** [comment]
I get the same error. I subscribe successfully to a channel (PrivateChannelEventListener.onSubscriptionSucceeded() gets called and i can see an "occupied" message in my pusher debug console), but events i send every 30 seconds are not received. In my case pusher runs in a background service in android. Could that be the reason? Before i had a singleton class which worked fine but after switching to a background service my onEvent isn't called.

**Comment by kn100** [comment]
Closing due to age
