### ISSUE TITLE
Unexistant dependency

### ISSUE THREAD

**Issue by jonathrodriguez** [pusher/pusher-websocket-java#96]
Dependency org.java-websocket:java-websocket:1.3.1 does not exist.
Atached build error and build gradle file

---
## Build error:

```
Error:A problem occurred configuring project ':android-module'.
> Could not resolve all dependencies for configuration ':android-module:_debugCompile'.
   > Could not find org.java-websocket:java-websocket:1.3.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.pom
         https://repo1.maven.org/maven2/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.jar
         file:/D:/Program Files/Android/sdk/extras/android/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.pom
         file:/D:/Program Files/Android/sdk/extras/android/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.jar
         file:/D:/Program Files/Android/sdk/extras/google/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.pom
         file:/D:/Program Files/Android/sdk/extras/google/m2repository/org/java-websocket/java-websocket/1.3.1/java-websocket-1.3.1.jar
     Required by:
         project:android-module:unspecified > project:java-core:unspecified > com.pusher:pusher-java-client:1.0.2
```
## java-core\build.gradle:

```
apply plugin: 'java'

repositories {
    mavenCentral()
    maven { url 'http://clojars.org/repo' } //Required for pusher
}

dependencies {
    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'com.google.code.gson:gson:2.6.2'

    //Pusher
    compile 'com.pusher:pusher-java-client:1.0.2'
}
```

**Comment by edwardotis** [comment]
For anyone coming here and using grails 2.5, the syntax for adding a maven repo changed.
The missing websockets library can be found by adding this line to your repositories{} in BuildConfig.groovy:

`        mavenRepo "https://clojars.org/repo"
`

More general info on repo configuration can be found here:

http://grails.github.io/grails-doc/2.5.4/guide/conf.html

        // uncomment these (or add new ones) to enable remote dependency resolution from public Maven repositories
        //mavenRepo "http://repository.codehaus.org"
        //mavenRepo "http://download.java.net/maven/2/"

**Comment by MGaetan89** [comment]
Is this issue still valid?
The latest version of `pusher-websocket-java` is 1.5.0 and uses `java-websocket` version 1.4.1.

**Comment by zmarkan** [comment]
Hi, 
we created our own fork of the Java Websocket library as the original repo wasn't maintained anymore. It's now using `com.pusher:java-websocket:1.4.1`(note the `com.pusher` group ID)
